// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fce002f0-4e3d-4a09-bd05-52a60429a655";

const char SSID[]               = "AB";    // Network SSID (name)
const char PASS[]               = "1234567890";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "2QxxHE25nyF8UvAl3RtCw3VCA";    // Secret device password


float current;
float flow;
float power;
float pressure;
float rpm;
float volt;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(current, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(flow, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(power, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pressure, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(rpm, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(volt, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
